### ISSUE TITLE
Add readme.md file to the project

### ISSUE THREAD

**Issue by ompanchwate** [Ayush-Bulbule/QuotesApp#1]
Adding a readme.md file will help others to know about this QuotesApp project.

**Comment by hemantwasthere** [comment]
@ompanchwate I would like to work on this issue

**Comment by bhagyashreetekade** [comment]
Assign me with this issue under Hacktoberfest 2022.

**Comment by Ayush-Bulbule** [comment]
issue resolved by @bhagyashreetekade
