### ISSUE TITLE
Add Loader

### ISSUE THREAD

**Issue by saksham-tiwari** [Ayush-Bulbule/QuotesApp#4]
Add loader till the time new quote is generated. Currently it shows only "Quote is Here".

**Comment by saksham-tiwari** [comment]
@Ayush-Bulbule Can you assign this issue to me?

**Comment by Ayush-Bulbule** [comment]
> @Ayush-Bulbule Can you assign this issue to me?
> 

Yes sure!!

**Comment by Ayush-Bulbule** [comment]
Let me solve the issue!

**Comment by Ayush-Bulbule** [comment]
Solved the issue by editing the tags please recheck!!

**Comment by Ayush-Bulbule** [comment]
Sure!
